name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build+test
        uses: cross-platform-actions/action@v0.23.0
        with:
          operating_system: freebsd
          version: '14.0'
          run: |
            CFLAGS="-O2 -pipe -Wshadow -Werror" make
            DESTDIR="${HOME}/work" make install
            ${HOME}/work/usr/local/bin/checkrc /etc/rc.conf
